from django.db import models

# Create your models here.
class Goods(models.Model):
    # id=models.AutoField()
    name=models.CharField(max_length=20)
    price=models.DecimalField(max_digits=7,decimal_places=2)
    shop_id=models.IntegerField()
    create_at=models.DateTimeField(auto_now_add=True)
    delete_at= models.DateTimeField()
    stock    = models.IntegerField(default=0)
    describe=models.CharField(max_length=50)
    standards=models.TextField()
    type = models.IntegerField()
class Shops(models.Model):
    # id=models.AutoField()
    name=models.CharField(max_length=20)
    type=models.CharField(max_length=20)
    location=models.CharField(max_length=20)
    business_id=models.IntegerField()
    create_at=models.DateTimeField(auto_now_add=True)
    delete_at= models.DateTimeField(null=True)
    initial_price = models.DecimalField(max_digits=7,decimal_places=2)
    distribution_price=models.DecimalField(max_digits=7,decimal_places=2)
    sales = models.IntegerField()
class Users(models.Model):
    # id=models.AutoField()
    uuid=models.CharField(max_length=200)
    openid=models.CharField(max_length=200)
    avatarUrl=models.TextField(null=True)
    nickName=models.CharField(max_length=20)
class Business(models.Model):
    # id=models.AutoField()
    username=models.CharField(max_length=20)
    userpwd=models.CharField(max_length=20)
    name=models.CharField(max_length=20)
    guid=models.CharField(max_length=100)
    student_id=models.CharField(max_length=20)
    student_pwd=models.CharField(max_length=20)
    student_name=models.CharField(max_length=20)
    people_id=models.CharField(max_length=20)
    email=models.EmailField()
    phone=models.CharField(max_length=20)
    create_at=models.DateTimeField(auto_now_add=True)
    delete_at= models.DateTimeField(null=True)
class Menu_Bns(models.Model):
    # id=models.AutoField()
    name=models.CharField(max_length=20)
    shop_id=models.IntegerField()
    delete_at = models.DateTimeField(null=True)
class Orders(models.Model):
    # id=models.AutoField()
    ordernum=models.CharField(max_length=20)
    shop_id=models.IntegerField()
    state=models.SmallIntegerField()
    create_at=models.DateTimeField(auto_now_add=True)
    complete_at=models.DateTimeField(null=True)
    total=models.DecimalField(max_digits=7,decimal_places=2)
    delete_at= models.DateTimeField(null=True)
    user_id=models.IntegerField()
    shop_name=models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    tel = models.CharField(max_length=11)
    user_name=models.CharField(max_length=11)
    payway=models.CharField(max_length=10)
    sendway = models.CharField(max_length=10)
    simpleInfo=models.CharField(max_length=200)
class Sales(models.Model):
    # id=models.AutoField()
    Orders_id=models.CharField(max_length=20)
    user_id=models.IntegerField()
    goods_id=models.IntegerField()
    shop_id=models.IntegerField()
    count = models.IntegerField()
    standards = models.TextField(null=True)
    goods_name = models.CharField(max_length=50)
    price=models.DecimalField(max_digits=7,decimal_places=2)
class Useraddrs(models.Model):
   user_id=models.IntegerField()
   address=models.CharField(max_length=100)
   door=models.CharField(max_length=50)
   name=models.CharField(max_length=10)
   tel=models.CharField(max_length=11)
   checked=models.IntegerField()

        