# Generated by Django 2.2 on 2018-08-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('userpwd', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('guid', models.CharField(max_length=100)),
                ('student_id', models.CharField(max_length=20)),
                ('student_pwd', models.CharField(max_length=20)),
                ('student_name', models.CharField(max_length=20)),
                ('people_id', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('delete_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=3)),
                ('shop_id', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('delete_at', models.DateTimeField()),
                ('stock', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Bns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('shop_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordernum', models.CharField(max_length=20)),
                ('shop_id', models.IntegerField()),
                ('business_id', models.IntegerField()),
                ('state', models.SmallIntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('complete_at', models.DateTimeField()),
                ('delete_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Orders_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('goods_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('business_id', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('delete_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade', models.IntegerField()),
                ('guid', models.CharField(max_length=100)),
            ],
        ),
    ]
